version: "3.7"

services:

  nginx:
    container_name: nep_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: prod
    restart: always
    volumes:
      - ./../public/:/usr/share/nginx/html:ro
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - php
      - mysql
    networks:
      - nep

  php:
    container_name: nep_php
    restart: always
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./../public/:/usr/share/nginx/html:delegated
    entrypoint: /usr/share/nginx/entrypoint.sh
    depends_on:
      - mysql
    networks:
      - nep

  mysql:
    container_name: nep_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./mysql/datastore:/var/lib/mysql:cached
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    networks:
      - nep

  node:
    container_name: nep_node
    build:
      context: ./node
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./../:/home/node/app:delegated
    working_dir: /home/node/app
    entrypoint: /home/node/entrypoint.sh
    environment:
      - NODE_ENV=prod
    networks:
      - nep

networks:
  nep:
    driver: bridge
