version: "3.7"

services:

  nginx:
    container_name: nep_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - nep-project:/app/nep:ro
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - php
      - mysql
    networks:
      - nep

  php:
    container_name: nep_php
    restart: always
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      target: dev
      args:
        - XDEBUG_ACTIVE=${XDEBUG_ACTIVE}
    volumes:
      - nep-project:/app/nep:delegated
    entrypoint: /app/entrypoint.sh
    depends_on:
      - mysql
    networks:
      - nep

  mysql:
    container_name: nep_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
        - nep-mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    networks:
      - nep

  node:
    container_name: nep_node
    build:
      context: ./node
      dockerfile: Dockerfile
      target: dev
    volumes:
      - nep-project:/app/nep:delegated
      - /app/nep/node_modules # Ignore
    working_dir: /app/nep
    entrypoint: /app/entrypoint.sh
    environment:
      - NODE_ENV=dev
    networks:
      - nep

networks:
  nep:
    driver: bridge

volumes:
  nep-mysql:
  nep-project:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../
      o: bind
