version: "3.7"

services:

  nginx:
    container_name: nep_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    restart: always
    volumes:
      - nep-project:/usr/share/nginx/html:nocopy
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - php
      - mysql
    networks:
      - nep

  php:
    container_name: nep_php
    restart: always
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      target: dev
      args:
        - XDEBUG_ACTIVE=${XDEBUG_ACTIVE}
    volumes:
      - nep-project:/usr/share/nginx/html:nocopy
    entrypoint: /usr/share/nginx/entrypoint.sh
    depends_on:
      - mysql
    networks:
      - nep

  mysql:
    container_name: nep_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
        - nep-mysql:/var/lib/mysql:nocopy
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    networks:
      - nep

  node:
    container_name: nep_node
    build:
      context: ./node
      dockerfile: Dockerfile
      target: dev
    volumes:
      - nep-root:/home/node/app:nocopy
    working_dir: /home/node/app
    entrypoint: /home/node/entrypoint.sh
    environment:
      - NODE_ENV=dev
    networks:
      - nep

networks:
  nep:
    driver: bridge

volumes:
  nep-mysql:
    external: true
  nep-project:
    external: true
  nep-root:
    external: true
